<div class="box-header with-border">
    <i class="fa fa-key"></i><h1 class="box-title">Roles (Perfiles) del Sistema</h1>
    <div class="box-tools"><?php echo Html::linkAction("crear", '<i class="fa fa-plus"></i>', 'class="btn btn-primary" title="Crear Rol"') ?></div>
</div>
<?php View::content() ?>
<div class="box-body">
	<?php
Table::headers('id', 'Rol', 'Roles de los que hereda privilegios', 'plantilla a usar', 'Estado', 'Editar', 'Eliminar');
Table::fields('id', 'rol', 'padres', 'plantilla');
Table::imgLink('figuras/circulo_verde.png|figuras/circulo_rojo.png', 'admin/roles/desactivar|admin/roles/activar', '', 'activo');
Table::imgLink('figuras/editar.png', 'admin/roles/editar');
Table::imgLinkConfirm('figuras/eliminar.png', 'admin/roles/eliminar', '', '¿Realmente desea Eliminar Este Rol?');
//Table::link('admin/usuarios/editar', 'Editar');
echo Table::create($roles, 'class="table table-bordered table-striped"');
?>
</div>

<div class="box-footer">
    
</div>
