<?php
echo Tag::js('jquery/jquery.tokeninput');
Tag::css('token-input');?>
<script type="text/javascript">
$(document).ready(function() 
{
    $("#detallemetrados_materiales_id").tokenInput("<?php echo '/'.$module_name.'/materiales/resultados'?>",
    {
        tokenLimit: 1,minChars: 3,
        <?php if(!empty($detallemetrados->materiales_id)){?>
        prePopulate: [
                {id: <?php echo $detallemetrados->materiales_id?>, name: "<?php echo $detallemetrados->getMateriales()->codigo.' '.$detallemetrados->getMateriales()->nombre?>"}
            ]
        <?php }?>
    });
});

</script>

<?php 
$exp_id = $partida->getPresupuestos()->getExpedientes()->expedientes_id;
$mod_id = $modulo->id;
$bloc_id = $partida->getPresupuestos()->expedientes_id;
$pres_id = $partida->presupuestos_id;
View::partial('menu_expediente',false,array('expediente_id'=>$exp_id)) ?>
<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-solid">
				<div class="box-header">
				    <h2 class="box-title"><?php echo $titulo?></h2>
				</div>
				<?php View::content();?>
				<div class="col-sm-9">
					<blockquote>
						<dl class="dl-horizontal">
					      <dt>Presupuesto: </dt><dd><?php echo $partida->getPresupuestos()->nombre?></dd>
					      <dt>Titulo: </dt><dd><?php echo $partida->getTitulopartidas()->titulo?></dd>
					      <dt>Medida: </dt><dd><?php echo $partida->getMedidas()->nombre?> (<?php echo $partida->getMedidas()->abr?>)</dd>
					      <dt>Tipo Partida</dt><dd><?Php echo $partida->getTipopartidas()->nombre?></dd>
					  	</dl>
					</blockquote>
				</div>
				<div class="col-sm-3">
					<?php if(!$crear && $detallemetrados->imagen){?>
					<div class="thumbnail">
						<?php echo Html::img('upload/'.$detallemetrados->imagen,'producto -info','class="margin" style=""'); ?>
					</div>
					<?php }else{
						if($codigo_tipo_de_partida === 'AC'){
							echo '<div class="thumbnail"><img src="/img/150x100.png" alt="..."></div>';
						}
					}?>
				</div>
				<div class="box-body">
					<?php if($codigo_tipo_de_partida === 'AC')
					{
						echo Form::openMultipart(NULL, 'role="form" class="form-horizontal"');
					}else{
						echo Form::open(NULL, 'post', 'role="form" class="form-horizontal"');
					}?>
					<?php echo Form::hidden('detallemetrados.id');?>
					<?php echo Form::hidden('detallemetrados.partidas_id',NULL,$partida->id);?>
					<?php echo Form::hidden('detallemetrados.estado',NULL,1);?>
					<?php echo Form::hidden('detallemetrados.parcial');?>
					<?php echo Form::hidden('detallemetrados.modulos_id',NULL,$modulo->id);?>
					<div class="row">
					<?php if($codigo_tipo_de_partida === 'AC'){?>
						<div class="col-sm-6">
						    <div class="form-group">
						    <?php echo Form::label('Elemento','detallemetrados.nombre','class="col-sm-3 control-label"');?>
						        <div class="col-sm-9">
						            <?php echo Form::text('detallemetrados.nombre','class="form-control" placeholder="nombre" required')?>
						        </div>
						    </div>
						</div>
						<div class="col-sm-6">
							<div class="form-group">
						    	<?php echo Form::label('Imagen','imagen','class="col-sm-3 control-label"');?>
						        <div class="col-sm-9">
						            <?php echo $crear ? Form::file('imagen','class="form-control" placeholder="Imagen" required accept="image/*"'):$detallemetrados->imagen?>
						            <br>
						            <span class="help-block no-margin">Formatos permitidos jpg, png, gif, jpeg Max 3MB</span>
						        </div>							
						    </div>	
						</div>
						
						<div class="col-sm-6">
							<div class="form-group">
						    	<?php echo Form::label('Tipo material','detallemetrados.tipo_material','class="col-sm-3 control-label"');?>
						        <div class="col-sm-9">
						            <?php echo Form::select('detallemetrados.tipo_material',array("Varilla"=>"Varilla","Estribo"=>"Estribo"),'class="form-control" placeholder="Tipo material"')?>
						        </div>
						    </div>
						</div>
						<div class="col-sm-6">
						    <div class="form-group">
						    <?php echo Form::label('Material','detallemetrados.materiales_id','class="col-sm-3 control-label"');?>
						        <div class="col-sm-9">
						            <?php echo Form::text('detallemetrados.materiales_id','class="form-control" placeholder="nombre" required')?>
						        </div>
						    </div>
						</div>
						<div class="col-sm-6">
							<div class="form-group">
						    	<?php echo Form::label('Cantidad de elementos','detallemetrados.cantidad_elementos','class="col-sm-3 control-label"');?>
						        <div class="col-sm-9">
						            <?php echo Form::text('detallemetrados.cantidad_elementos','class="form-control calcular" placeholder="Cantidad de elementos"')?>
						        </div>
						    </div>
						</div>
						<div class="col-sm-6">
							<div class="form-group">
						    	<?php echo Form::label('Nº de veces del tipo','detallemetrados.numero_de_veces','class="col-sm-3 control-label"');?>
						        <div class="col-sm-9">
						            <?php echo Form::text('detallemetrados.numero_de_veces','class="form-control calcular" placeholder="Nº de veces"')?>
						        </div>
						    </div>
						</div>

					<?php }else{?>
						<div class="col-sm-6">
						    <div class="form-group">
						    <?php echo Form::label('Nombre','detallemetrados.nombre','class="col-sm-3 control-label"');?>
						        <div class="col-sm-9">
						            <?php echo Form::text('detallemetrados.nombre','class="form-control" placeholder="nombre" required')?>
						        </div>
						    </div>
						</div>
						<?php } ?>


						<?php if($codigo_tipo_de_partida==='FL'){?>
						<div class="col-sm-6">
							<div class="form-group">
						    	<?php echo Form::label('Cantidad','detallemetrados.cantidad_elementos','class="col-sm-3 control-label"');?>
						        <div class="col-sm-9">
						            <?php echo Form::text('detallemetrados.cantidad_elementos','class="form-control calcular" placeholder="Cantidad de elementos"')?>
						        </div>
						    </div>
						</div>
						<?php }?>

						<?php if($codigo_tipo_de_partida==='NN'){?>
						<div class="col-sm-6">
							<div class="form-group">
						    	<?php echo Form::label('Nº de veces','detallemetrados.numero_de_veces','class="col-sm-3 control-label"');?>
						        <div class="col-sm-9">
						            <?php echo Form::text('detallemetrados.numero_de_veces','class="form-control calcular" placeholder="Nº de veces"')?>
						        </div>
						    </div>
						</div>
						<div class="col-sm-6">
						    <div class="form-group">
						    <?php echo Form::label('Ancho','detallemetrados.Ancho','class="col-sm-3 control-label"');?>
						        <div class="col-sm-9">
						            <?php echo Form::text('detallemetrados.ancho','class="form-control calcular" placeholder="Ancho"')?>
						        </div>
						    </div>
						</div>
						<div class="col-sm-6">
						    <div class="form-group">
						    	<?php echo Form::label('Altura','detallemetrados.altura','class="col-sm-3 control-label"');?>
						        <div class="col-sm-9">
						            <?php echo Form::text('detallemetrados.altura','class="form-control calcular" placeholder="Altura"')?>
						        </div>
						    </div>						
						</div>
						<div class="col-sm-6">
							<div class="form-group">
						    	<?php echo Form::label('Factor','detallemetrados.factor','class="col-sm-3 control-label"');?>
						        <div class="col-sm-9">
						            <?php echo Form::text('detallemetrados.factor','class="form-control calcular" placeholder="Factor"')?>
						        </div>
						    </div>
						</div>
						<div class="col-sm-6">
						    <div class="form-group">
						    <?php echo Form::label('Largo','detallemetrados.largo','class="col-sm-3 control-label"');?>
						        <div class="col-sm-9">
						            <?php echo Form::text('detallemetrados.largo','class="form-control calcular" placeholder="Largo"')?>
						        </div>
						    </div>
						</div>

						<?php }?>
						
					</div>
					<div class="col-sm-12" style="border-bottom: solid #ccc 1px;">
						<div class="form-group">
						    <div class="with-padding pull-right">
						    	<br>
						    	<?php if(!$crear)echo Html::linkAction('update_photo/'.$partida->id.'/'.$detallemetrados->id,'Editar imagen','class="btn"');?>
						    	<?php echo Form::submit('Guardar Datos','class="btn btn-primary"') ?>
						    </div>
						</div>
					</div>
					<?php echo Form::close();?>
					<div class="col-sm-12 with-padding" >
						<?Php 
						
						echo Form::open('apps/metrados/terminar/'.$exp_id.'/'.$mod_id.'/'.$bloc_id.'/'.$pres_id);
						echo Form::hidden('partida.id');
						echo Form::hidden('partida.presupuestos_id');
						echo Form::hidden('partida.titulopartidas_id');
						echo Form::hidden('partida.medidas_id');
						echo Form::hidden('partida.tipopartidas_id');
						?>
						<div id="reporte-detalles">
						<table class="table">
							<caption>Detalle del metrado </caption>
							<thead>
							<?php if($codigo_tipo_de_partida==='AC'){?>
								<tr>
									<th>Codigo</th>
									<th>Foto</th>
									<th>Elemento</th>
									<th>Tipo</th>
									<th>Nº veces Tipo</th>
									<th>Cantidad de elemento</th>
									<th>Largo</th>
									<th>Factor</th>
									<th>Parcial</th>
									<th>Accion</th>
								</tr>
							<?php }
							if($codigo_tipo_de_partida==="NN"){?>
								<tr>
									<th>Nº</th>
									<th>Nombre</th>
									<th>Nº veces</th>
									<th>Largo</th>
									<th>Ancho</th>
									<th>Altura</th>
									<th>Factor</th>
									<th>Parcial</th>
									<th>Accion</th>
								</tr>
							<?php }?>
							<?php if($codigo_tipo_de_partida==="FL"){?>
								<tr>
									<th>Nº</th>
									<th>Nombre</th>
									<th>Cantidad</th>
									<th>Accion</th>
								</tr>
							<?php }?>
							</thead>
							<tbody>
							<?php 
							$total=0;
							$n=0;
							foreach($metrados as $metro){
								$n++;
								$largo = $metro->largo ? $metro->largo : 1;
								$ancho = $metro->ancho ? $metro->ancho : 1;
								$altura = $metro->altura ? $metro->altura: 1;
								$total=$total+$metro->parcial;
								?>
								<?php if($codigo_tipo_de_partida==="AC"){?>
								<tr>
									<td><?php echo $metro->getMateriales()->codigo;?></td>
									<td class="thumbnail"><?php echo $metro->imagen ? Html::img('upload/'.$metro->imagen,'producto -info','class="margin" style="width: 100px;"'): '<img src="/img/150x100.png" alt="...">'; ?></td>
									<td><?php echo $metro->getMateriales()->nombre;?></td>
									<td><?php echo $metro->tipo_material ?></td>
									<td align="center"><?Php echo $metro->numero_de_veces?></td>
									<td align="center"><?php echo $metro->cantidad_elementos?></td>
									<td align="right"><?php echo $metro->largo ? number_format($largo,4): '-'?></td>

									<td  align="center"><?php echo $metro->factor ?></td>
									<td align="right"><?php echo number_format($metro->numero_de_veces*($largo*$ancho*$altura),4);echo ' '.$partida->getMedidas()->abr;?></td>
									<td align="center"><?php echo Html::linkAction('editar/'.$partida->id.'/'.$metro->id,' <i class="fa fa-edit" style="font-size:25px;"></i>','class="__no_mostrar"');?></td>
								</tr>
								<?php }
								if($codigo_tipo_de_partida==="FL"){?>
								<tr>
									<td><?php echo $n;?></td>
									<td><?php echo $metro->nombre;?></td>
									<td align="right"><?php echo $metro->cantidad_elementos;?></td>
									<td align="center"><?php echo Html::linkAction('editar/'.$partida->id.'/'.$metro->id,' <i class="fa fa-edit" style="font-size:25px;"></i>','class="__no_mostrar"');?></td>
								</tr>
								<?Php }
								if($codigo_tipo_de_partida==="NN"){?>
								<tr>
									<td><?php echo $n;?></td>
									<td><?php echo $metro->nombre;?></td>
									<td><?Php echo $metro->numero_de_veces?></td>
									<td align="right"><?php echo $metro->largo ? number_format($largo,4): '-'?></td>
									<td align="right"><?php echo $metro->ancho ? number_format($ancho,4) : '-'?></td>
									<td align="right"><?php echo $metro->altura ? number_format($altura,4) : '-'?></td>
									<td align="right"><?php echo number_format($metro->numero_de_veces*($largo*$ancho*$altura),4);echo ' '.$partida->getMedidas()->abr;?></td>
									<td align="center"><?php echo Html::linkAction('editar/'.$partida->id.'/'.$metro->id,' <i class="fa fa-edit" style="font-size:25px;"></i>','class="__no_mostrar"');?></td>
								</tr>
								<?php }?>

							<?php }?>
							</tbody>
							<tfoot>
								<?php if($codigo_tipo_de_partida==="AC"){?>
								<tr>
									<td colspan="10">
										<table class="table">
											<tbody>
												<tr>
													<td align="right"><b>Material:</b></td>
													<?php foreach($totales as $tm){?>
													<td align="right"><b><?php echo $tm->nombre?></b></td>
													<?php }?>
												</tr>
												<tr>
													<td align="right"><b>Parcial:</b></td>
													<?php foreach($totales as $tp){?>
													<td align="right"><?Php echo number_format($tp->parcial,4)?></td>
													<?php }?>
												</tr>
												<tr>
													<td align="right"><b>Kilogramos del acero</b></td>
													<?php foreach($totales as $tk){?>
													<td align="right"><?php echo number_format($tk->peso,4)?></td>
													<?php }?>
												</tr>
												<tr>
													<td align="right"><b>Kilos total</b></td>
													<?php foreach($totales as $tkt){?>
													<td align="right"><?php echo number_format($tkt->kilos,4)?></td>
													<?php }?>
												</tr>
												<tr>
													<td align="right"><b>Nº de varillas de acero de 9ml</b></td>
													<?php foreach($totales as $tv){?>
													<td align="right"><?php echo number_format($tv->cantidad_varilla,4)?></td>
													<?php }?>
												</tr>
											</tbody>
										</table>
									</td>
								</tr>
							<?php }
							if($codigo_tipo_de_partida==="NN"){?>
								<tr>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td align="right"><b>Total:</b></td>
									<td align="right"><?php echo number_format($total,4);echo ' '.$partida->getMedidas()->abr;?></td>
									<td></td>
								</tr>
							<?php }?>
							</tfoot>
						</table>
						</div>
					</div>
				</div>
				<div class="box-footer with-border">
					<div class="pull-right">
				    <?php 
				    echo Form::hidden('partida.metrado',NULL,$total);
				    echo Form::hidden('partida.detallemetrados');
				    echo Form::submit('Terminar','class="btn btn-primary"') ?></div>
				    <?php echo Form::close();?>
				</div>
				<script type="text/javascript">
					$(document).ready(function(){
					    $('#partida_detallemetrados').val($("#reporte-detalles").html());
					});
					function calcular() {
					  var veces = $( "#detallemetrados_numero_de_veces" ).val();
					  var largo = $( "#detallemetrados_largo" ).val();
					  var ancho = $( "#detallemetrados_ancho" ).val();
					  var altura = $( "#detallemetrados_altura" ).val();
					  var cantidad_elementos = $( "#detallemetrados_cantidad_elementos" ).val();
					  if(!largo){largo=1;}
					  if(!ancho){ancho=1;}
					  if(!altura){altura=1;}
					  if(!cantidad_elementos){cantidad_elementos=1;}
					  return veces*(largo*ancho*altura*cantidad_elementos);
					}
					$( ".calcular" ).change(function() {
					  $("#detallemetrados_parcial" ).val(calcular());
					  
					});
				</script>
			</div>
		</div>
	</div>
</section>