<?php
echo Tag::js('jquery/jquery.tokeninput');
Tag::css('token-input');?>
<script type="text/javascript">


</script>
<?php 
$exp_id = $partida->getPresupuestos()->getExpedientes()->expedientes_id;
$mod_id = $modulo->id;
$bloc_id = $partida->getPresupuestos()->expedientes_id;
$pres_id = $partida->presupuestos_id;?>
<section class="content">
	<div class="row">
	<?php View::partial('menu_expediente',false,array('expediente_id'=>$exp_id)) ?>
		<div class="col-md-12">
			<div class="box box-solid">
				<div class="box-header">
				    <h2 class="box-title"><?php echo $titulo?></h2>
				</div>
				<blockquote>
					<dl class="dl-horizontal">
				      <dt>Presupuesto: </dt><dd><?php echo $partida->getPresupuestos()->nombre?></dd>
				      <dt>Titulo: </dt><dd><?php echo $partida->getTitulopartidas()->titulo?></dd>
				      <dt>Medida: </dt><dd><?php echo $partida->getMedidas()->nombre?> (<?php echo $partida->getMedidas()->abr?>)</dd>
				  	</dl>
				</blockquote>
				<div class="box-body">
					<?php echo Form::open(NULL, 'post', 'role="form" class="form-horizontal"');?>
						<?php echo Form::hidden('detalleanalisis.id');?>
						<?php echo Form::hidden('detalleanalisis.partidas_id',NULL,$partida->id);?>
						<?php echo Form::hidden('detalleanalisis.estado',NULL,1);?>
						<?php echo Form::hidden('detalleanalisis.parcial');?>
						<?php echo Form::hidden('detalleanalisis.modulos_id',NULL,$modulo->id);?>
						<?php 
						echo Form::hidden('partida.id');
						echo Form::hidden('partida.presupuestos_id');
						echo Form::hidden('partida.titulopartidas_id');
						echo Form::hidden('partida.tipopartidas_id');
						echo Form::hidden('partida.medidas_id');?>
					<div class="row">

						<div class="col-sm-6">
						    <div class="form-group">
						    <?php echo Form::label('Medida','detalleanalisis.medidas_id','class="col-sm-3 control-label"');?>
						        <div class="col-sm-9">
						            <?php echo Form::dbSelect('detalleanalisis.medidas_id','nombre',NULL,'seleccione','class="form-control" placeholder="Nº de veces"')?>
						        </div>
						    </div>
						</div>
						<div class="col-sm-6">
						    <div class="form-group">
						    <?php echo Form::label('Material','detalleanalisis.materiales_id','class="col-sm-3 control-label"');?>
						        <div class="col-sm-9">
						            <?php echo Form::text('detalleanalisis.materiales_id','class="form-control" placeholder="Materiales"')?>
						        </div>
						    </div>
						</div>
						<div class="col-sm-6">
						    <div class="form-group">
						    <?php echo Form::label('Cuadrilla','detalleanalisis.cuadrilla','class="col-sm-3 control-label"');?>
						        <div class="col-sm-9">
						            <?php echo Form::input('decimal','detalleanalisis.cuadrilla','class="form-control calcular" placeholder="Cuadrilla"')?>
						        </div>
						    </div>
						</div>
						<div class="col-sm-6">
						    <div class="form-group">
						    <?php echo Form::label('Cantidad','detalleanalisis.cantidad','class="col-sm-3 control-label"');?>
						        <div class="col-sm-9">
						            <?php echo Form::input('decimal','detalleanalisis.cantidad','class="form-control" placeholder="Cantidad"')?>
						        </div>
						    </div>
						</div>
						<div class="col-sm-6">
						    <div class="form-group">
						    <?php echo Form::label('Precio','detalleanalisis.precio','class="col-sm-3 control-label calcular"');?>
						        <div class="col-sm-9">
						            <?php echo Form::input('number','detalleanalisis.precio','class="form-control calcular" placeholder="Precio"')?>
						        </div>
						    </div>
						</div>
						<div class="col-sm-6">
						    <div class="form-group">
						    <?php echo Form::label('Rendimiento','partida.rendimiento','class="col-sm-3 control-label"');?>
						        <div class="col-sm-9">
						            <?php echo Form::input('number','partida.rendimiento','class="form-control calcular" placeholder="Rendimiento"')?>
						        </div>
						    </div>
						</div>
						<div class="col-sm-12">
						    <div>
						    	<?php echo Form::submit('Guardar Datos','class="btn btn-primary pull-right"') ?>
						    </div>
						</div>
					</div>
					<hr>
					<?php echo Form::close();?>
					<div class="col-sm-12">
						<br>
						<?Php 
						echo Form::open('apps/analisis/terminar/'.$exp_id.'/'.$mod_id.'/'.$bloc_id.'/'.$pres_id);
						echo Form::hidden('partida.id');
						echo Form::hidden('partida.presupuestos_id');
						echo Form::hidden('partida.titulopartidas_id');
						echo Form::hidden('partida.tipopartidas_id');
						echo Form::hidden('partida.medidas_id');
						?>
						<div role="separator" class="divider">
							<div class="col-sm-3">
								Rendimiento <b><?php echo $partida->getMedidas()->abr?>/DIA</b>
							</div>
							<div class="col-sm-2">
								<?php echo $partida->rendimiento;?>
							</div>
							<div class="col-sm-3">
								Costo unitario directo por: <?php echo $partida->getMedidas()->abr?>
							</div>
							<div class="col-sm-3">
								<b><?php echo $partida->costo ? number_format($partida->costo,4): '-';?></b>
							</div>
						</div>
						<div id="reporte-detalleanalisis">
							<table class="table">
								<caption>Detalle de Costo unitario </caption>
								<thead>
									<tr>
										<th>Codigo</th>
										<th>Descripcion recurso</th>
										<th>Unidad</th>
										<th>Cuadrilla</th>
										<th>Cantidad</th>
										<th>Precio S/</th>
										<th>Parcial</th>
										<th>Accion</th>
									</tr>
								</thead>
								<tbody>
									<?php 
									
									
									foreach($tipos as $tipo){
										$n=0;
										foreach($analisis as $item){?>
										<?php 
											if($tipo->id==$item->getMateriales()->getTipomateriales()->tipomateriales_id){
												$n++;
												$cantidad = $item->cantidad ? $item->cantidad : 0;
												$precio = $item->precio ? $item->precio : 0;
												
											?>
											<?php if($n==1)echo "<tr><td colspan='8'><b>".$tipo->nombre.$tipo->simbologia."</b></td></tr>"; ?>
											<tr>
												<td><?php echo $item->getMateriales()->getCodigoCompleto();?></td>
												<td><?php echo $item->getMateriales()->nombre;?></td>
												<td><?Php echo $item->getMedidas()->nombre?></td>
												<td align="right"><?php echo $item->cuadrilla ? number_format($item->cuadrilla,3):'-'?></td>
												<td align="right"><?php echo number_format($cantidad,4);?></td>
												<td align="right">S/ <?php echo $item->precio ? number_format($precio,4) : '-'?></td>
												<td align="right">S/ <?php echo $item->parcial ? number_format($item->parcial,4):'-';?></td>
												<td align="center">
													<?php 
													echo Html::linkAction('editar/'.$partida->id.'/'.$item->id,' <i class="fa fa-edit" style="font-size:15px;"></i>','title="Editar detalle de analsis"');
													echo Html::linkAction('eliminar_analisis/'.$partida->id.'/'.$item->id,' <i class="fa fa-minus-square" style="font-size:15px;"></i>','title="Eliminar detalle de analsis" onclick="return confirm(\'¿Está seguro?\')"' );
													if($partida->getTipopartidas()->codigo==='FL' && $tipo->simbologia==='SE'){
														echo Html::linkAction('calcular_flete/'.$partida->id.'/'.$item->id.'/'.$item->get_calculoflete(),' <i class="fa fa-road" style="font-size:15px;"></i>','title="Calcular el flete"');
														if($item->get_calculoflete()) echo Html::linkAction('eliminar_flete/'.$partida->id.'/'.$item->get_calculoflete(),' <i class="fa fa-trash" style="font-size:15px;"></i>','title="Eliminar calculo del flete" onclick="return confirm(\'¿Está seguro?\')"');
													};?></td>
											</tr>
									<?php   } 
										}?>
								<?php }?>
								</tbody>
								<tfoot>
									<tr>
										<td></td>
										<td></td>
										<td></td>
										<td></td>
										<td></td>
										<td align="right"><b>Total:</b></td>
										<td align="right">S/ <?php echo number_format($total_parcial_partida,4);?></td>
										<td></td>
									</tr>
								</tfoot>
							</table>
						</div>
					</div>
				</div>
				<div class="box-footer with-border">
					<div class="pull-right">
				    <?php 
				    echo Form::hidden('partida.costo','',$total_parcial_partida);
				    echo Form::hidden('partida.detalleanalisis');
				    echo Form::hidden('partida.metrado');
				    echo Form::submit('Terminar','class="btn btn-primary"') ?></div>
				    <?php echo Form::close();?>
				</div>
			<script type="text/javascript">
			$(document).ready(function() 
			{
				function calCantidad(){
					var cuadrilla = $( "#detalleanalisis_cuadrilla").val();
					var rendimiento = $( "#partida_rendimiento").val();
					//console.log(cuadrilla,rendimiento);
					return (cuadrilla*8)/rendimiento;
				}	
				function calcular() {
				  var cantidad = $( "#detalleanalisis_cantidad" ).val();
				  var precio = $( "#detalleanalisis_precio" ).val();
				  return cantidad*precio;
				}
				$(".calcular").change(function() {

				 if(tipo_codigo=='EQ' || tipo_codigo=="MO"){
				 	alert('calcular')
				  	$("#detalleanalisis_cantidad").val(calCantidad());
				 }
				 $("#detalleanalisis_parcial" ).val(calcular());

				});
				$('#partida_detalleanalisis').val($("#reporte-detalleanalisis").html());
				var tipo_codigo = '0';
			    $("#detalleanalisis_materiales_id").tokenInput("<?php echo '/'.$module_name.'/materiales/resultados'?>",
			    {
			        tokenLimit: 1,
			        minChars: 3,
			        <?php if(!empty($detalleanalisis->materiales_id)){?>
			        prePopulate: [
			                {id: <?php echo $detalleanalisis->materiales_id?>, name: "<?php echo $detalleanalisis->getMateriales()->getCodigoCompleto().' '.$detalleanalisis->getMateriales()->nombre?>",tipo_codigo:"<?php echo $detalleanalisis->getMateriales()->getTipomateriales()->getTipomateriales()->simbologia?>"}
			            ],
			        <?php }?>
			        onAdd: function (item) {
	                    alert("codigo " + item.tipo_codigo);
	                    tipo_codigo=item.tipo_codigo;
	                    if(tipo_codigo=='EQ' || tipo_codigo=='MO'){
						  	$("#detalleanalisis_cantidad").attr('readonly', 'readonly');
						}
	                },
	                onDelete: function (item) {
	                    alert("codigo " + item.tipo_codigo);
	                    tipo_codigo=item.tipo_codigo;
	                    if(tipo_codigo=='EQ' || tipo_codigo=="MO"){
						  	$("#detalleanalisis_cantidad").attr('readonly', '');
						}
	                }

			    });
			});
			</script>
			</div>
		</div>
	</div>
</section>