<?php 
$Ex = new Expedientes();
$registros= $Ex->getTipoExp();
?>

<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar" style="position: fixed;">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="/img/<?php echo Auth::get('picture') ?>" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p><?php echo Auth::get('nombres') ?></p>

                <a href="#"><i class="fa fa-circle text-success"></i> Conectado</a>
            </div>
        </div>
        <div class="col-md-12 menu_expediente no-padding">
          <?php View::renderMenu(Menu::APP,3,'class="sidebar-menu"');?>      <!-- /. box -->
        </div>
        <!-- sidebar menu: : style can be found in sidebar.less -->
    </section>
    <!-- /.sidebar -->
</aside>