<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="/img/<?php echo Auth::get('picture') ?>" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p><?php echo Auth::get('nombres') ?></p>

                <a href="#"><i class="fa fa-circle text-success"></i> Conectado</a>
            </div>
        </div>
        
        
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <?php //View::renderMenu(Menu::SPATRICIA,3,'class="sidebar-menu"') ?>
        <?php if($modulo=='admin')View::renderMenu(Menu::BACKEND,3,'class="sidebar-menu"') ?>
        <?php if($modulo=='apps')
        {
            View::renderMenu(Menu::APP,3,'class="sidebar-menu"');
            //View::renderExp();
        }?>
        
    </section>
    <!-- /.sidebar -->
</aside>