
<div class="box-header with-border">
    <i class="fa fa-industry"></i><h1 class="box-title">Listado de Empresas</h1>
    <div class="box-tools"><?php echo Html::linkAction("crear", '<i class="fa fa-plus"></i>','class="btn btn-primary" title="Crear Empresa"') ?></div>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div> 
<div class="box-body">
	<?php
	Table::headers('id', 'Nombre', 'Razon Social', 'Ruc', 'Direccion');
	Table::headers('Estado', 'Editar','Eliminar');
	Table::fields('id', 'nombre', 'razonsocial', 'ruc', 'direccion');
	Table::imgLink('figuras/circulo_verde.png|figuras/circulo_rojo.png', 'admin/aclempresas/desactivar|admin/aclempresas/activar', '', 'activo');
	Table::imgLink('figuras/editar.png', 'admin/aclempresas/editar');
	Table::imgLinkConfirm('figuras/eliminar.png', 'admin/aclempresas/eliminar', '', '¿Realmente desea Eliminar Esta Empresa?');
	//Table::link('admin/aclempresas/borrar','editar');
	echo Table::create($aclempresas, 'class="table table-bordered"');
	?>
</div>

<div class="form-actions">
    <?php //echo Html::linkAction("crear", 'Crear Empresa','class="btn btn-primary"') ?>
</div>
