<div class="box-header with-border">
    <h2 class="box-title"><?php echo $titulo?></h2>
</div>
<div class="box-body">
	<div class="row">
		<div class="col-sm-6">
			<div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Recently Added Products</h3>

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <ul class="products-list product-list-in-box">
                <?php foreach ($new_productos as $new_p) { ?>
                  <li class="item">
                    <div class="product-img">
                      <img src="/img/150x100.png" alt="Product Image">
                    </div>
                    <div class="product-info">
                      <a href="javascript:void(0)" class="product-title"><?php echo $new_p->nombre?>
                        <span class="label label-warning pull-right"><?php echo $new_p->precio?></span></a>
                      <span class="product-description"><?php echo $new_p->detalle?> <?php echo $new_p->peso?>
                          </span>
                    </div>
                  </li>
              <?php }?>
                <!-- /.item -->
                
              </ul>
            </div>
            <!-- /.box-body -->
            <div class="box-footer text-center">
              <a href="javascript:void(0)" class="uppercase">View All Products</a>
            </div>
            <!-- /.box-footer -->
          </div>
		</div><div class="col-sm-6">
			<div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Recently Added Products</h3>

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <ul class="products-list product-list-in-box">
                 <?php foreach ($mis_precisos as $precios) { ?>
                  <li class="item">
                    <div class="product-img">
                      <img src="/img/150x100.png" alt="Product Image">
                    </div>
                    <div class="product-info">
                      <a href="javascript:void(0)" class="product-title"><?php echo $new_p->nombre?>
                        <span class="label label-warning pull-right">$1800</span></a>
                      <span class="product-description">
                            <?php echo $new_p->detalle?> <?php echo $new_p->peso?>
                          </span>
                    </div>
                  </li>
              <?php }?>
              </ul>
            </div>
            <!-- /.box-body -->
            <div class="box-footer text-center">
              <a href="javascript:void(0)" class="uppercase">View All Products</a>
            </div>
            <!-- /.box-footer -->
          </div>
		</div>
	</div>
</div>
<div class="box-footer">
	
</div>