<div class="modal-content modal-default">
  <div class="modal-header with-border">
    <button type="button" class="close" data-dismiss="modal"><i class="fa fa-close"></i></button>
    <h4 class="modal-title"><?Php echo $material->getCodigoCompleto(); ?> <?php echo $material->nombre?> </h4>
  </div>
  <!-- /.modal-header -->
  <div class="modal-body">
    <div class="table-responsive">
      <table class="table no-margin">
        <thead>
          <tr>
            <th>Fecha</th>
            <th>Precio</th>
            <th>Status</th>
            <th>opc</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($precios as $precio) {?>
          <tr>
            <td><a href="javascript:;"><?php echo $precio->fecha?></a></td>
            <td><?Php echo 'S/ '.number_format($precio->precio,'2','.','')?></td>
            <td><span class="label label-success"><?php echo $estados[$precio->estado];?></span></td>
            <td>
              
            </td>
          
          </tr>
          <?Php } ?>
          
        </tbody>
      </table>
    </div>
    <!-- /.table-responsive -->
  </div>
  <!-- /.modal-body -->
  <div class="modal-footer clearfix">
     <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  </div>
  <!-- /.modal-footer -->
</div>