<div class="box-header with-border">
    <h2 class="box-title"><?php echo $titulo?></h2>
</div>
<div class="box-body">
  <div>
    <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
        <?php foreach($tipos as $tip){?>
          <li <?php echo $tipo->id==$tip->id? 'class="active"':'';?>><a href="/tiendas/mis_productos/listar/<?php echo $tip->id?>/0/"><?php echo $tip->nombre ?></a></li>
        <?php }?>
        </ul>
        <div class="tab-content">
            <div class="tab-panel active" id="<?php echo $tipo->simbologia?>">
                <div class="row">
                <div class="col-lg-3">
                    <h4>Tipo Materiales <?php //echo Html::linkAction('crear/'.$tipo->id.'/'.$indice->id,' <i class="fa fa-plus" style="font-size:15px;"></i>','class="btn"');?></h4>
                    <div class="input-group">
                      <input type="text" name="q_tipo" id="q_tipo" class="form-control" placeholder="Buscar...">
                          <span class="input-group-btn">
                            <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                            </button>
                          </span>
                    </div>
                    <ul class="todo-list" id="lista_tipos">
                    <?php foreach($indices as $indi){?>
                        <li class="active"><?php echo Html::linkAction('listar/'.$tipo->id.'/'.$indi->id,$indi->nombre,'class=""')?> 
                        
                    <?php }?>   
                    </ul>
                </div>
                <div class="col-lg-9">
                    <?php if($indice){?>
                    <h4><?php echo $indice->nombre?> <?php echo Html::linkAction('crear/'.$tipo->id.'/'.$indice->id,' <i class="fa fa-plus" style="font-size:15px;"></i>','class="btn"');?></h4>
                    <?php print_r($materiales);?>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Codigo</th>
                                <th>Nombre</th>
                                <th>Descripcion</th>
                                <th>Precio</th>
                                <th>Peso</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>

                        <tbody>
                            <?php $n=0;foreach($materiales->items as $item):
                            $n++;?>
                            <tr>
                                <td><?php echo $n;?></td>
                                <td><?php echo $item->getCodigoCompleto();?>.<?php echo $item->id?></td>
                                <td><?php echo $item->nombre?></td>
                                <td><?php echo $item->descripcion?></td>
                                <td><?php echo $item->precio?></td>
                                <td><?php echo $item->peso?></td>
                                <td><?php echo Html::linkAction('editar/'.$tipo->id.'/'.$indice->id.'/'.$item->id,' <i class="fa fa-edit" style="font-size:25px;"></i>');?></td>
                            </tr>
                            <?php endforeach;?>
                        </tbody>
                    </table>
                    <?php }?>
                </div>
                </div>
            </div>
        </div>
    </div>  
  </div>
</div>
<div class="box-footer">
    
</div>
<script type="text/javascript">
$(document).ready(function() 
{
    $("#q_tipo").keydown(function(event) {
        var q =$(this).val();
        if(q){
            $("#lista_tipos").load( "/apps/materiales/tipo_lista/<?php echo $id;?>/"+q);
        }
    });
    $('.openModal').on('click',function(){
    var params = $(this).attr('data-params');
    var _url = $(this).attr('data-url');
    $('.modal-body').load(_url+params,function(){
        $('#tipomateriales_modal').modal({show:true});
    });
});
});

</script>

<!-- Modal -->
<div class="modal fade" id="tipomateriales_modal" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h4 class="modal-title">Modal with Dynamic Content</h4>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>