<div class="box-header">
    <h1>Configuraci&oacute;n de la tienda</h1>
</div>
<?php View::content() ?>
API de GOOGLE MAPS AIzaSyAYpXm-DxqBfCuO9NEwLlNSvjXUns3458k ///
AIzaSyAuvN_GraUsuwlb5inwY96mr0OCmapgkJM
<div class="box-body">
<ul class="nav nav-tabs">
    <li class="active"><a href="#datos-tienda" data-toggle="tab">Datos de la tienda</a></li>
    
</ul>
<div class="tab-content">
    <div id="datos-personales" class="tab-pane active">
        <?php echo Form::open(NULL, 'post', 'role="form" class="form-horizontal"');?>
        <fieldset>
            <legend>Configurar Datos</legend>
            
            <div class="col-sm-6">
                <div class="form-group">
                <?php echo Form::label('Nombre','aclempresas.nombre','class="col-sm-3 control-label"');?>
                    <div class="col-sm-9">
                        <?php echo Form::text('tienda.nombre','class="form-control" placeholder="Nombre" required')?>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                <?php echo Form::label('Ruc','aclempresas.ruc','class="col-sm-3 control-label"');?>
                    <div class="col-sm-9">
                        <?php echo Form::text('tienda.ruc','class="form-control" placeholder="Ruc" required')?>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                <?php echo Form::label('Razon social','aclempresas.razonsocial','class="col-sm-3 control-label"');?>
                    <div class="col-sm-9">
                        <?php echo Form::text('tienda.razonsocial','class="form-control" placeholder="Razon social" required')?>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                <?php echo Form::label('Direccion','aclempresas.direccion','class="col-sm-3 control-label"');?>
                    <div class="col-sm-9">
                        <?php echo Form::text('tienda.direccion','class="form-control" placeholder="Direccion" required')?>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                <?php echo Form::label('Telefono','aclempresas.telefonos','class="col-sm-3 control-label"');?>
                    <div class="col-sm-9">
                        <?php echo Form::text('tienda.telefonos','class="form-control" placeholder="Telefono" required')?>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                <?php echo Form::label('Celular','aclempresas.telefonos1','class="col-sm-3 control-label"');?>
                    <div class="col-sm-9">
                        <?php echo Form::text('tienda.telefonos1','class="form-control" placeholder="Celular" required')?>
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
            <div class="form-actions">
                <?php echo Form::submit('Guardar Cambios', 'name="datos_personas" class="btn btn-primary"') ?>
            </div>
            </div>
        </fieldset>
        <?php echo Form::close() ?>
    </div>

</div>
</div>
 