<div class="box-header">
	<h2 class="box-title"><?php echo $titulo?> <?php echo $tipo->nombre ?></h2>
</div>
<div class="box-body">
	<div class="row">
		<div class="col-sm-10">
	    <?php echo Form::open(NULL, 'post', 'role="form" class="form-horizontal"');?>
	    <?php echo Form::hidden('materiales.id');?>
	    <?php echo Form::hidden('materiales.estado',NULL,1);?>

	    <div class="form-group">
	    	<?php echo Form::label('Indice Unificado','materiales.tipomateriales_id','class="col-sm-2 control-label"');?>
	        <div class="col-sm-10">
	        	<?php echo Form::dbSelect('materiales.tipomateriales_id','nombre',array('tipomateriales','find','conditions: estado=1 AND tipomateriales_id='.$tipo->id),'Seleccione','class="form-control"',$indices_id)?>
	        </div>
	    </div>
	    <div class="form-group">
	    	<?php echo Form::label('Codigo','materiales.codigo','class="col-sm-2 control-label"');?>
	        <div class="col-sm-10">
	        	<?php echo Form::text('materiales.codigo','class="form-control calcular" placeholder="Codigo"')?>
	        </div>
	    </div>
	    <div class="form-group">
	    	<?php echo Form::label('Nombre','materiales.nombre','class="col-sm-2 control-label"');?>
	        <div class="col-sm-10">
	        	<?php echo Form::text('materiales.nombre','class="form-control calcular" placeholder="Nombre"')?>
	        </div>
	    </div>
	    <div class="form-group">
	    	<?php echo Form::label('Descripcion','materiales.descripcion','class="col-sm-2 control-label"');?>
	        <div class="col-sm-10">
	        	<?php echo Form::textArea('materiales.descripcion','class="form-control calcular" placeholder="Descripcion"')?>
	        </div>
	    </div>
	    <div class="form-group">
	    	<?php echo Form::label('Precio','materiales.precio','class="col-sm-2 control-label"');?>
	        <div class="col-sm-10">
	        	<?php echo Form::text('materiales.precio','class="form-control calcular" placeholder="Precio"')?>
	        </div>
	    </div>
	    <div class="form-group">
	    	<?php echo Form::label('Peso','materiales.peso','class="col-sm-2 control-label"');?>
	        <div class="col-sm-10">
	        	<?php echo Form::text('materiales.peso','class="form-control calcular" placeholder="peso"')?>
	        </div>
	    </div>
	    <div class="form-group">
	    	<div class="pull-right">
	    		<?php echo Html::linkAction('index/'.$tipo->id.'/'.$indices_id,'Regresar al listado','class="btn"');?>
	    		<?php echo Form::submit('Guardar Datos','class="btn btn-primary"') ?>
	    	</div>	
	    </div>
		<?php echo Form::close();?>
		</div>
		<div class="col-sm-3"></div>
	</div>	
</div>
<div class="box-footer">
	
</div>		
			