<div class="box-header with-border">
    <h2 class="box-title"><?php echo $titulo?></h2>
</div>
<div class="box-body">
  <div>
  	<div class="nav-tabs-custom">
  		<ul class="nav nav-tabs">
        <?php foreach($tipos as $tip){?>
          <li <?php echo $tipo->id==$tip->id? 'class="active"':'';?>><a href="/apps/materiales/index/<?php echo $tip->id?>#<?php echo $tip->simbologia ?>"><?php echo $tip->nombre ?></a></li>
        <?php }?>
        </ul>
        <div class="tab-content">
        	<div class="tab-panel active" id="<?php echo $tipo->simbologia?>">
        		<div class="row">
        		<div class="col-lg-2">
        			<h4>Tipo Materiales <?php //echo Html::linkAction('crear/'.$tipo->id.'/'.$indice->id,' <i class="fa fa-plus" style="font-size:15px;"></i>','class="btn"');?></h4>
        			<div class="input-group">
			          <input type="text" name="q_tipo" id="q_tipo" class="form-control" placeholder="Buscar...">
			              <span class="input-group-btn">
			                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
			                </button>
			              </span>
			        </div>
	    			<ul class="todo-list" id="lista_tipos">
	    			<?php foreach($indices as $indi){?>
	    				<li><?php echo Html::linkAction('index/'.$tipo->id.'/'.$indi->id.'#'.$tipo->simbologia,$indi->nombre,'class=""')?></li>
	    			<?php }?>	
	    			</ul>
	    		</div>
    			<div class="col-lg-10">
	    			<?php if($indice){?>
	    			<h4><?php echo $indice->nombre?> <?php echo Html::linkAction('crear/'.$tipo->id.'/'.$indice->id,' <i class="fa fa-plus" style="font-size:15px;"></i>','class="btn"');?></h4>
			    	<table class="table table-bordered">
						<thead>
							<tr>
								<th>#</th>
								<th>Codigo</th>
								<th>Nombre</th>
								<th>Descripcion</th>
								<th>Precio</th>
								<th>Peso</th>
								<th>Acciones</th>
							</tr>
						</thead>

						<tbody>
							<?php $n=0;foreach($materiales as $item):
							$n++;?>
							<tr>
								<td><?php echo $n;?></td>
								<td><?php echo $item->getCodigoCompleto();?>.<?php echo $item->id?></td>
								<td><?php echo $item->nombre?></td>
								<td><?php echo $item->descripcion?></td>
								<td><?php echo $item->precio?></td>
								<td><?php echo $item->peso?></td>
								<td><?php echo Html::linkAction('editar/'.$tipo->id.'/'.$indice->id.'/'.$item->id,' <i class="fa fa-edit" style="font-size:25px;"></i>');?></td>
							</tr>
							<?php endforeach;?>
						</tbody>
					</table>
					<?php }?>
				</div>
				</div>
        	</div>
        </div>
  	</div>	
  </div>
</div>
<div class="box-footer">
	
</div>
<script type="text/javascript">
$(document).ready(function() 
{
    $("#q_tipo").keydown(function(event) {
    	var q =$(this).val();
    	if(q){
	    	$("#lista_tipos").load( "/apps/materiales/tipo_lista/<?php echo $id;?>/"+q);
	    }
    });
});

</script>