<div class="box-header with-border">
    <h2 class="box-title"><?php echo $titulo?></h2>
</div>
<div class="box-body">
  <div>
  	<div class="nav-tabs-custom">
  		<ul class="nav nav-tabs">
        <?php foreach($tipos as $tip){?>
          <li <?php echo $tipo->id==$tip->id? 'class="active"':'';?>><a href="/apps/materiales/index/<?php echo $tip->id?>#<?php echo $tip->simbologia ?>"><?php echo $tip->nombre ?></a></li>
        <?php }?>
        </ul>
        <div class="tab-content">
        	<div class="tab-panel active" id="<?php echo $tipo->simbologia?>">
        		
    			<div class="btn-group">
    			<?php foreach($indices as $indi){?>
    				<?php echo Html::linkAction('index/'.$tipo->id.'/'.$indi->id.'#'.$tipo->simbologia,$indi->nombre,'class="btn margin"')?>
    			<?php }?>
    					
    			</div>
    			<?php if($indice){?>
    			<h4><?php echo $indice->nombre?> <?php echo Html::linkAction('crear/'.$tipo->id.'/'.$indice->id,' <i class="fa fa-plus" style="font-size:15px;"></i>','class="btn"');?></h4>
		    	<table class="table table-bordered">
					<thead>
						<tr>
							<th>#</th>
							<th>Codigo</th>
							<th>Nombre</th>
							<th>Descripcion</th>
							<th>Precio</th>
							<th>Peso</th>
							<th>Acciones</th>
						</tr>
					</thead>

					<tbody>
						<?php $n=0;foreach($materiales as $item):
						$n++;?>
						<tr>
							<td><?php echo $n;?></td>
							<td><?php echo $item->codigo?></td>
							<td><?php echo $item->nombre?></td>
							<td><?php echo $item->descripcion?></td>
							<td><?php echo $item->precio?></td>
							<td><?php echo $item->peso?></td>
							<td><?php echo Html::linkAction('editar/'.$item->id,' <i class="fa fa-edit" style="font-size:25px;"></i>');?></td>
						</tr>
						<?php endforeach;?>
					</tbody>
				</table>
				<?php }?>
        	</div>
        </div>
  	</div>	
  </div>
</div>
<div class="box-footer">
	foot
</div>