<?php echo Tag::js('jquery/jquery-menu-editor');
echo Tag::js('bs-iconpicker/js/bootstrap-iconpicker');
Tag::css('bs-iconpicker/css/bootstrap-iconpicker');?>
<?php View::partial('menu_expediente',false,array('expediente_id'=>0)) ?>
<div class="box-header">
    <h2 class="box-title"><?php echo $titulo?> <small>Del Mes de <?php echo $meses[date("m")];?></small></h2>
</div>
<?php print_r($array_titulo);?>
<div class="box-body">        
    <div class="row">

        <div class="col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">Edit item</div>
                <div class="panel-body">
                    <form id="frmEdit" class="form-horizontal">
                        <div class="form-group">
                            <label for="text" class="col-sm-2 control-label">Text</label>
                            <div class="col-sm-10">
                                <div class="input-group">
                                    <input type="text" class="form-control item-menu" name="text" id="text" placeholder="Text">
                                    <div class="input-group-btn">
                                        <button type="button" id="myEditor_icon" class="btn btn-default" data-iconset="fontawesome"></button>
                                    </div>
                                    <input type="hidden" name="icon" class="item-menu">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="href" class="col-sm-2 control-label">URL</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control item-menu" id="href" name="href" placeholder="URL">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="target" class="col-sm-2 control-label">Target</label>
                            <div class="col-sm-10">
                                <select name="target" id="target" class="form-control item-menu">
                                    <option value="_self">Self</option>
                                    <option value="_blank">Blank</option>
                                    <option value="_top">Top</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="title" class="col-sm-2 control-label">Tooltip</label>
                            <div class="col-sm-10">
                                <input type="text" name="title" class="form-control item-menu" id="title" placeholder="Tooltip">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    <button type="button" id="btnUpdate" class="btn btn-primary" disabled><i class="fa fa-refresh"></i> Update</button>
                    <button type="button" id="btnAdd" class="btn btn-success"><i class="fa fa-plus"></i> Add</button>
                </div>
            </div>
            
        </div>
        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-heading clearfix"><h5 class="pull-left">Menu</h5>
                    <div class="pull-right">
                        <button id="btnReload" type="button" class="btn btn-default">
                            <i class="glyphicon glyphicon-triangle-right"></i> Load Data</button>
                    </div>
                </div>
                <div class="panel-body" id="cont">
                    <ul id="myEditor" class="sortableLists list-group">
                    </ul>
                </div>
            </div>
            <div class="form-group">
                <button id="btnOut" type="button" class="btn btn-success"><i class="glyphicon glyphicon-ok"></i> Output</button>
            </div>
            <div class="form-group"><textarea id="out" class="form-control" cols="50" rows="10"></textarea>
            </div>
        </div>
    </div>
</div>
<script>
            jQuery(document).ready(function () {
                // menu items
                var strjson = [{"href":"http://home.com","icon":"fa fa-home","text":"Home", "target": "_top", "title": "My Home"},{"icon":"fa fa-bar-chart-o","text":"Opcion2"},{"icon":"fa fa-cloud-upload","text":"Opcion3"},{"icon":"fa fa-crop","text":"Opcion4"},{"icon":"fa fa-flask","text":"Opcion5"},{"icon":"fa fa-map-marker","text":"Opcion6"},{"icon":"fa fa-search","text":"Opcion7","children":[{"icon":"fa fa-plug","text":"Opcion7-1","children":[{"icon":"fa fa-filter","text":"Opcion7-1-1"}]}]}];
                //icon picker options
                var iconPickerOptions = {searchText: 'Buscar...', labelHeader: '{0} de {1} Pags.'};
                //sortable list options
                var sortableListOptions = {
                    placeholderCss: {'background-color': 'cyan'}
                };

                var editor = new MenuEditor('myEditor', {listOptions: sortableListOptions, iconPicker: iconPickerOptions, labelEdit: 'Edit'});
                editor.setForm($('#frmEdit'));
                editor.setUpdateButton($('#btnUpdate'));
                
                $('#btnReload').on('click', function () {
                    editor.setData(strjson);
                });

                $('#btnOut').on('click', function () {
                    var str = editor.getString();
                    $("#out").text(str);
                });

                $("#btnUpdate").click(function(){
                    editor.update();
                });

                $('#btnAdd').click(function(){
                    editor.add();
                });
            });
        </script>