<?php echo Tag::js('jquery/jquery.sortable');
//echo Tag::js('bs-iconpicker/js/bootstrap-iconpicker');
//Tag::css('bs-iconpicker/css/bootstrap-iconpicker');?>
<?php View::partial('menu_expediente',false,array('expediente_id'=>0)) ?>
<script type="text/javascript">
    $(function () {
          var oldContainer;
          $("ol.nested_with_switch").sortable({
            group: 'nested_with_switch',
            cursor: "move",
            connectWith:".nested_with_switch",
            afterMove: function (placeholder, container) {
              if(oldContainer != container){
                if(oldContainer)
                  oldContainer.el.removeClass("active");
                container.el.addClass("active");

                oldContainer = container;
              }
            },
            onDrop: function ($item, container, _super) {
              var data = group.sortable("serialize").get();
              alert(data);
              var jsonString = JSON.stringify(data, null, ' ');

              $('#serialize_output2').text(jsonString);
              _super($item, container);
            }
            
          });
    });
var group = $("ol.serialization").sortable({
  group: 'serialization',
  delay: 500,
  onDrop: function ($item, container, _super) {
    var data = group.sortable("serialize").get();

    var jsonString = JSON.stringify(data, null, ' ');

    $('#serialize_output2').text(jsonString);
    _super($item, container);
  }
});
</script>
<br>
<div id="serialize_output2"></div>
<div class="box padding" id="nested">
          <h2>Toggable nested lists</h2>
          <div class="row">
            <div class="col-sm-12 example" style="display: block;">
              

            </div>
            <div class="col-sm-4">
              
              <ol class="nested_with_switch vertical">
                <li class="btn btn-block">
                  Item 1
                </li >
                <li class="btn btn-block">
                  Item 2
                </li >
                <li class="btn btn-block">
                  Item 3
                </li>
                <li class="btn btn-block">
                  Item 4
                  <ol class="nested_with_switch vertical">
                    <li class="btn btn-block">Item 3.1</li>
                    <li class="btn btn-block">Item 3.2</li>
                    <li class="btn btn-block">Item 3.3</li>
                    <li class="btn btn-block">Item 3.4</li>
                    <li>Item 3.5</li>
                    <li>Item 3.6</li>
                  </ol>
                </li>
                <li>
                  Item 5
                </li>
                <li>
                  Item 6
                </li>
              </ol>
            </div>
            <div class="col-sm-4">
              
              <ol class="nested_with_switch vertical">
                <li>
                  Item 1
                </li>
                <li>
                  Item 2
                </li>
                <li>
                  Item 3
                </li>
                <li>
                  Item 4
                  <ol>
                    <li>Item 3.1</li>
                    <li>Item 3.2</li>
                    <li>Item 3.3</li>
                    <li>Item 3.4</li>
                    <li>Item 3.5</li>
                    <li>Item 3.6</li>
                  </ol>
                </li>
                <li>
                  Item 5
                </li>
                <li>
                  Item 6
                </li>
              </ol>
            </div>
          </div>
        </div>