<?php echo Tag::js('jquery/jquery.sortable');
//echo Tag::js('bs-iconpicker/js/bootstrap-iconpicker');
//Tag::css('bs-iconpicker/css/bootstrap-iconpicker');?>
<?php View::partial('menu_expediente',false,array('expediente_id'=>0)) ?>
<script type="text/javascript">
    $(function () {
          var oldContainer;
          $("ol.nested_with_switch").sortable({
            group: 'nested_with_switch',
            cursor: "move",
            connectWith:".nested_with_switch",
            afterMove: function (placeholder, container) {
              if(oldContainer != container){
                if(oldContainer)
                  oldContainer.el.removeClass("active");
                container.el.addClass("active");

                oldContainer = container;
              }
            },
            onDrop: function ($item, container, _super) {
              var data = group.sortable("serialize").get();
              alert(data);
              var jsonString = JSON.stringify(data, null, ' ');

              $('#serialize_output2').text(jsonString);
              _super($item, container);
            }
            
          });
    });
var group = $("ol.serialization").sortable({
  group: 'serialization',
  delay: 500,
  onDrop: function ($item, container, _super) {
    var data = group.sortable("serialize").get();

    var jsonString = JSON.stringify(data, null, ' ');

    $('#serialize_output2').text(jsonString);
    _super($item, container);
  }
});
</script>
<br>
<div id="serialize_output2"></div>
<div class="box padding" id="nested">
          <h2>Toggable nested lists</h2>
          <div class="row">
            <div class="col-sm-12 example" style="display: block;">
              

            </div>
            <div class="col-sm-10">
              <?php 
              $bloque_id=$bloque? $bloque->id : 0;
              $presupuesto_id=$presupuesto? $presupuesto->id : 0;
              function obtener_titulos($array_titulo,$modulo,$expediente,$presupuesto,$bloque_id,$li,$cod,$partidas){
                foreach ($array_titulo as $ti) {
                  $codigo= $cod ? $cod.'.'.$ti['codigo_titulo'] : $ti['codigo_titulo'];
                  $li.='<li>';
                  $li.=''.$presupuesto->codigo.' '.$codigo.'';
                  $li.='';
                  $li.='<b>'.$ti['titulo'].'</b>';
                  $ol_li='<ol class="nested_with_switch vertical">';
                  $PP=$partidas->get_titulos_partidas_all($presupuesto->id,$ti['id']);
                  $n=0;
                  foreach($PP as $partida){
                    $n++;
                      $ol_li.='<li>';
                      $ol_li.='<td>'.$presupuesto->codigo.' '.$codigo.'.'.$n.'</li>';
                      
                    }
                  $ol_li.='</ol>';
                  $li.=$ol_li;
                  if($ti['total_sub']){
                    $li=obtener_titulos($ti['subtitulos'],$modulo,$expediente,$presupuesto,$bloque_id,$li,$codigo,$partidas);
                  }else{
                  }

                  $li.='</li>';
                }
                return $li;
              }
              
              ?>
              <ol class="nested_with_switch vertical">
                <?php echo obtener_titulos($array_titulo,$modulo,$expediente,$presupuesto,$bloque_id,$tr='',0,$partidas);?>
               
              </ol>
            </div>
          </div>
        </div>